### ISSUE TITLE
"Buffer to small for input line lengths"

### ISSUE THREAD

**Issue by vyx-lucy-kaplun** [twolinin/longphase#26] opened 2023-04-09 02:45 UTC
Hi, I am running longphase with ONT long reads data and getting an error "Buffer to small for input line lengths". How can I fix that?

**Comment by twolinin** [comment] 2023-04-09 05:50
Hi @vyx-lucy-kaplun 

Can you please provide the command used so that we can identify the cause of the issue?

thanks

**Comment by vyx-lucy-kaplun** [comment] 2023-04-10 17:35
@twolinin Thank you for the speedy reply! 

The command I am using is 
`longphase_linux-x64 phase -s nano_snp.vcf.gz  --sv-file nano_sv_cutesv.vcf.gz   -b nano.sorted.bam   -r hg38.no_alt.fa   -t 12 -o longphase_combined.phased.  --ont`

File sizes are:
92M      nano_snp.vcf.gz
29M     nano_sv_cutesv.vcf.gz
192G    nano.sorted.bam

Unfortunately, I cannot share the files due to some security guidelines.

Thank you again!

**Comment by twolinin** [comment] 2023-04-11 02:06
Hi, @vyx-lucy-kaplun 

This issue may be caused by one of the lines in the vcf.gz file exceeding the default buffer size of 1M. This problem will be addressed in the next version update. For now, you can try uncompressing the file and running longphase again as a temporary solution.

Thanks.

**Comment by vyx-lucy-kaplun** [comment] 2023-04-11 18:17
@twolinin Thank you!

**Closed** 2024-04-14 14:49 UTC
